# Generated by Django 6.0.6 on 2026-06-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('preparing', 'En preparación'), ('shipped', 'Enviado'), ('out_for_delivery', 'En reparto'), ('delivered', 'Entregado')], default='pending', max_length=20),
        ),
    ]
